[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
LineSearch = "87fe0de2-c867-4266-b59a-2f0a94fc965b"

[compat]
Documenter = "1.16.1"
DocumenterCitations = "1.4.1"
LineSearch = "0.1.4"
